- name: OpenSearch Configuration | Copy Configuration File
  ansible.builtin.blockinfile:
    block: "{{ lookup('template', 'templates/opensearch-{{ cluster_type }}.yml') }}"
    dest: "{{ os_conf_dir }}/opensearch.yml"
    backup: true
    state: present
    create: true
    marker: "## {mark} opensearch main configuration ##"
    owner: "{{ os_user }}"
    group: "{{ os_user }}"
    mode: 0600

- name: OpenSearch Configuration | Copy jvm.options File for Instance
  ansible.builtin.template:
    src: jvm.options
    dest: "{{ os_conf_dir }}/jvm.options"
    owner: "{{ os_user }}"
    group: "{{ os_user }}"
    mode: 0600
    force: true