---

- name: OpenSearch Install | Download opensearch {{ os_version }}
  get_url:
    url: "{{ os_download_url }}/{{ os_version }}/opensearch-{{ os_version }}-linux-x64.tar.gz"
    dest: "/tmp/opensearch.tar.gz"
  register: download

- name: OpenSearch Install | Create opensearch user
  user:
    name: "{{ os_user }}"
    state: present
    shell: /bin/bash
  when: download.changed

- name: OpenSearch Install | Create home directory
  file:
    path: "{{ os_home }}"
    state: directory
    owner: "{{ os_user }}"
    group: "{{ os_user }}"
  when: download.changed

- name: OpenSearch Install | Extract the tar file
  command: chdir=/tmp/ tar -xvzf opensearch.tar.gz -C "{{ os_home }}" --strip-components=1
  when: download.changed

- name: OpenSearch Install | Copy Configuration File
  template:
    src: "opensearch-{{ cluster_type }}.yml"
    dest: "{{os_conf_dir}}/opensearch.yml"
    owner: "{{ os_user }}"
    group: "{{ os_user }}"
    mode: 0600
    backup: yes

- name: OpenSearch Install | Copy jvm.options File for Instance
  template:
    src: jvm.options
    dest: "{{os_conf_dir}}/jvm.options"
    owner: "{{ os_user }}"
    group: "{{ os_user }}"
    mode: 0600
    force: yes

- name: OpenSearch Install | create systemd service
  template:
    src: opensearch.service
    dest: "{{ systemctl_path }}/opensearch.service"
