---

## Here we are going to use self-signed certificates for Transport (Node-Node communication) & REST API layer
## Using searchguard offline TLS tool to create node & root certificates
- name: Security Plugin configuration | Create local temporary directory for certificates generation
  local_action:
    module: file
    path: /tmp/opensearch-nodecerts
    state: directory
  run_once: true
  register: configuration

- name: Security Plugin configuration | Download certificates generation tool
  local_action:
    module: get_url
    url: https://search.maven.org/remotecontent?filepath=com/floragunn/search-guard-tlstool/1.5/search-guard-tlstool-1.5.tar.gz
    dest: /tmp/opensearch-nodecerts/search-guard-tlstool.tar.gz
  run_once: true
  when: configuration.changed

- name: Security Plugin configuration | Extract the certificates generation tool
  local_action: command chdir=/tmp/opensearch-nodecerts tar -xvf search-guard-tlstool.tar.gz
  run_once: true
  when: configuration.changed

- name: Security Plugin configuration | Make the executable file
  local_action:
    module: file
    dest: /tmp/opensearch-nodecerts/tools/sgtlstool.sh
    mode: a+x
  run_once: true
  when: configuration.changed

- name: Security Plugin configuration | Prepare the certificates generation template file
  local_action:
    module: template
    src: tlsconfig.yml
    dest: /tmp/opensearch-nodecerts/config/tlsconfig.yml
  run_once: true
  when: configuration.changed

- name: Security Plugin configuration | Generate the node & admin certificates in local
  local_action:
    module: command /tmp/opensearch-nodecerts/tools/sgtlstool.sh -c /tmp/opensearch-nodecerts/config/tlsconfig.yml -ca -crt -t /tmp/opensearch-nodecerts/config/
  run_once: true
  when: configuration.changed

- name: Security Plugin configuration | Copy the node & admin certificates to opensearch nodes
  copy:
    src: "/tmp/opensearch-nodecerts/config/{{ item }}"
    dest: "{{ os_conf_dir }}"
    mode: 0600
  with_items:
    - root-ca.pem
    - root-ca.key
    - "{{ inventory_hostname }}.key"
    - "{{ inventory_hostname }}.pem"
    - "{{ inventory_hostname }}_http.key"
    - "{{ inventory_hostname }}_http.pem"
    - admin.key
    - admin.pem
  when: configuration.changed

- name: Security Plugin configuration | Copy the security configuration file 1 to cluster
  blockinfile:
    block: "{{ lookup('template', 'templates/security_conf.yml') }}"
    dest: "{{ os_conf_dir }}/opensearch.yml"
    backup: yes
    insertafter: EOF
    marker: "## {mark} OpenSearch Security common configuration ##"
  when: configuration.changed

- name: Security Plugin configuration | Copy the security configuration file 2 to cluster
  blockinfile:
    block: "{{ lookup('file', '/tmp/opensearch-nodecerts/config/{{ inventory_hostname }}_elasticsearch_config_snippet.yml') }}"
    dest: "{{ os_conf_dir }}/opensearch.yml"
    backup: yes
    insertafter: EOF
    marker: "## {mark} opensearch Security Node & Admin certificates configuration ##"
  when: configuration.changed

- name: Security Plugin configuration | Prepare the opensearch security configuration file
  command: sed -i 's/searchguard/plugins.security/g' {{ os_conf_dir }}/opensearch.yml
  when: configuration.changed

- name: Security Plugin configuration | Set the file ownerships
  file:
    dest: "{{ os_home }}"
    owner: "{{ os_user }}"
    group: "{{ os_user }}"
    recurse: yes

- name: Security Plugin configuration | Set the folder permission
  file:
    dest: "{{ os_conf_dir }}"
    owner: "{{ os_user }}"
    group: "{{ os_user }}"
    mode: 0700

- name: Security Plugin configuration | Restart opensearch with security configuration
  systemd:
    name: opensearch
    state: restarted
    enabled: yes

- name: Pause for 3 seconds to provide sometime for OpenSearch start
  pause:
    seconds: 3

- name: Security Plugin configuration | Copy the opensearch security internal users template
  template:
    src: internal_users.yml
    dest: "{{ os_sec_plugin_conf_path }}/internal_users.yml"
    mode: 0644
  run_once: true
  when: configuration.changed

- name: Security Plugin configuration | Set the Admin user password
  shell: >
    sed -i '/hash: / s,{{ admin_password }},'$(bash {{ os_sec_plugin_tools_path }}/hash.sh -p {{ admin_password }} | tail -1)','
    {{ os_sec_plugin_conf_path }}/internal_users.yml
  environment:
    JAVA_HOME: "{{ os_home }}/jdk"
  run_once: true
  when: configuration.changed

- name: Security Plugin configuration | Set the kibanaserver user pasword
  shell: >
    sed -i '/hash: / s,{{ kibanaserver_password }},'$(bash {{ os_sec_plugin_tools_path }}/hash.sh -p {{ kibanaserver_password }} | tail -1)','
    {{ os_sec_plugin_conf_path }}/internal_users.yml
  environment:
    JAVA_HOME: "{{ os_home }}/jdk"
  run_once: true
  when: configuration.changed

- name: Security Plugin configuration | Initialize the opensearch security index in opensearch
  shell: >
    bash {{ os_sec_plugin_tools_path }}/securityadmin.sh
    -cacert {{ os_conf_dir }}/root-ca.pem
    -cert {{ os_conf_dir }}/admin.pem
    -key {{ os_conf_dir }}/admin.key
    -f {{ os_sec_plugin_conf_path }}/internal_users.yml
    -nhnv -icl
    -h {{ hostvars[inventory_hostname]['ip'] }}
  environment:
    JAVA_HOME: "{{ os_home }}/jdk"
  run_once: true
  when: configuration.changed

- name: Security Plugin configuration | Cleanup local temporary directory
  local_action:
    module: file
    path: /tmp/opensearch-nodecerts
    state: absent
  run_once: true
  when: configuration.changed
