---
_meta:
  type: "internalusers"
  config_version: 2

admin:
  hash: "{{ opensearch_admin_password_bcrypt }}"
  reserved: true
  backend_roles:
  - "admin"
  description: "admin user"

kibanaserver:
  hash: "{{ opensearch_kibanaserver_password_bcrypt }}"
  reserved: true
  description: "kibanaserver user"
